CREATE DATABASE IF NOT EXISTS userflow_db;

USE userflow_db;

CREATE TABLE User (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Age INT NOT NULL,
    BirthDate DATE NOT NULL
);